---
language: c
compiler:
  - clang
  - gcc
before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y protobuf-c-compiler libprotobuf-c0-dev libio-socket-inet6-perl libwww-perl
script:
  - cd src && ./configure && time make -j2
  - cd ../tests && mkdir -p logs data
  - time make travistest || cat logs/aprsc.log
