---
language: c
compiler:
  - clang
  - gcc
before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y protobuf-c-compiler libprotobuf-c0-dev
script:
  - cd src && ./configure && make
  - cd ../tests && make test
