---
language: c
compiler:
  - clang
  - gcc
before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y protobuf-c-compiler libprotobuf-c0-dev libio-socket-inet6-perl
script:
  - cd src && ./configure && time make
  - cd ../tests && (time make quicktest || cat logs/aprsc.log)
